const User = require('./user')
const Recipe = require('./recipe')
const Ingredient = require('./ingredient')

const Brownie = new Recipe('Brownie', 'easy', '30 min', 4)
const Maria = new User('Maria', 'maria@gmail.com', 'potato')
const chocolate = new Ingredient('chocolate', 200, 'grams')
Maria.likeRecipe(Brownie)
Brownie.addIngredients(chocolate)
Brownie.addDiet('Vegetarian, GF')
console.log(Maria)
console.log(Brownie)

const flour = new Ingredient('flour', 500, 'grams', 'grams')
console.log(flour.amount)
console.log(flour.changeMeasurement())
